### ISSUE TITLE
EndOfStreamException in debugging

### ISSUE THREAD

**Issue by IvanovNiko** [BogdanovKirill/RtspClientSharp#24]
Hi.

I am recieving an exception below when I assign breakpoint in debugger an code debugging.
What is meaning this exception?

RtspClientSharp.Rtsp.RtspClientException: Receive error ---> System.IO.EndOfStreamException: End of TPKT stream
   at RtspClientSharp.Tpkt.TpktStream.<FindNextPacketAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RtspClientSharp.Tpkt.TpktStream.<ReadAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RtspClientSharp.Rtsp.RtspClientInternal.<ReceiveOverTcpAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RtspClientSharp.Rtsp.RtspClientInternal.<ReceiveAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RtspClientSharp.RtspClient.<ReceiveAsync>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at RtspClientSharp.RtspClient.<ReceiveAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by BogdanovKirill** [comment]
It means that connection was closed by RTSP server because you program was suspended by debugger

**Comment by IvanovNiko** [comment]
Thanks. I understood.
Is the recieve timeout  a server option? Can it be assign on the client side?

**Comment by IvanovNiko** [comment]
I saw parameters in ConnectionParameters class:
ConnectTimeout
ReceiveTimeout
CancelTimeout 

It seems that this is what I need.

**Comment by BogdanovKirill** [comment]
> Thanks. I understood.
> Is the recieve timeout a server option? Can it be assign on the client side?

No. That timeouts should be adjusted on server side.

**Comment by BogdanovKirill** [comment]
> I saw parameters in ConnectionParameters class:
> ConnectTimeout
> ReceiveTimeout
> 
> It seems that this is what I need.

It's your (client) timeouts, not server.

**Comment by IvanovNiko** [comment]
> It's your (client) timeouts, not server.
Ok, thanks.
